CREATED_CHOICE = 10
PAID_CHOICE = 20
FAILED_PAYMENT_CHOICE = 30
DELIVERED_CHOICE = 40
FAILED_DELIVERY_CHOICE = 50
REVERSED_CHOICE = 60
FAILED_REVERSED_CHOICE = 70

PAYMENT_STATUS_CHOICES = (
    (CREATED_CHOICE, 'creada'),
    (PAID_CHOICE, 'pagada'),
    (FAILED_PAYMENT_CHOICE, 'pago fallido'),
    (DELIVERED_CHOICE, 'entregada'),
    (FAILED_DELIVERY_CHOICE, 'entrega fallida'),
    (REVERSED_CHOICE, 'pago reversado'),
    (FAILED_REVERSED_CHOICE, 'devolución fallida'),
)
