CREATED_CHOICE = 10
PAID_CHOICE = 20
DELIVERED_CHOICE = 30
REVERSED_PAYMENT_CHOICE = 40

ORDER_STATUS_CHOICES = (
    (CREATED_CHOICE, 'creada'),
    (PAID_CHOICE, 'pagada'),
    (DELIVERED_CHOICE, 'entregada'),
    (REVERSED_PAYMENT_CHOICE, 'pago reversado'),
)
