# Generated by Django 2.1.3 on 2018-11-28 12:52

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'creada'), (20, 'pagada'), (30, 'entregada'), (40, 'pago reversado')], default=10, verbose_name='estado')),
                ('products', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='productos')),
                ('total_value', models.IntegerField(verbose_name='valor total de la compra')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('status', models.CharField(max_length=128, verbose_name='estado')),
                ('status_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de actualización del estado')),
                ('create_response', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='información creacion del pago en Tpaga')),
                ('canceled_at', models.DateTimeField(null=True, verbose_name='fecha de cancelación del pago')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Payment', verbose_name='pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
