# Generated by Django 2.1.3 on 2018-11-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['created_at'], 'verbose_name': 'Solicitud de pago', 'verbose_name_plural': 'Solicitudes de pago'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación'),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_token',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='token para evitar solicitudes repetidas'),
        ),
        migrations.AddField(
            model_name='payment',
            name='request_token',
            field=models.CharField(default='', max_length=128, verbose_name='token de solicitud de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'creada'), (20, 'pagada'), (30, 'pago fallido'), (40, 'entregada'), (50, 'entrega fallida'), (60, 'pago reversado'), (60, 'devolución fallida')], default=10, verbose_name='estado'),
        ),
    ]
