# Generated by Django 2.1.3 on 2018-11-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181129_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='idempotency_token',
            field=models.CharField(max_length=128, unique=True, verbose_name='token para evitar solicitudes repetidas'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='request_token',
            field=models.CharField(max_length=128, verbose_name='token de solicitud de pago'),
        ),
    ]
