# Generated by Django 2.1.3 on 2018-11-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181129_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('description', models.CharField(max_length=512, verbose_name='descripción')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='imagen')),
                ('price', models.PositiveIntegerField(verbose_name='precio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
    ]
