# Generated by Django 2.1.3 on 2018-11-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181129_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'creada'), (20, 'pagada'), (30, 'pago fallido'), (40, 'entregada'), (50, 'entrega fallida'), (60, 'pago reversado'), (70, 'devolución fallida')], default=10, null=True, verbose_name='estado'),
        ),
    ]
